let date=new Date()
console.log(date)
console.table([date.toString('en-IN',{timeZone:'Asia/Kolkata'}),date.toDateString(),date.toISOString(),date.toLocaleDateString(),date.toLocaleString('en-IN',{weekday:"long",timeZone:'Asia/Kolkata'})])
let date2=new Date(2025,2,26,16,30,0)
console.log(date2.toLocaleString())
let timestamp=Date.now()
console.log(timestamp/(1000*60*60*24))
console.log(`the current year is ${date2.getFullYear()} and my birthday at ${date2.getMonth()} and the date was ${date2.getDate()} and the day was ${date2.getDay()}`)
let a=new Array(1,2,3,4,5,6)
console.log(a,a.length)
a.push(7)
a.push(8)
console.log(a)
a.pop()
a.unshift(9)
console.log(a)
a.shift()
a.shift()
console.log(a)
let b=a.join()
console.log(b,typeof(b[0]))
c=a.slice(3,7)
console.log(c,a)
d=a.splice(3,5)
console.log(d,a)
let arr1=["thor","captain","ironman"]
let arr2=["batman","flash","superman"]
let arr3=arr1.concat(arr2)
console.log(arr3)
//arr1.push(arr2)
console.log(arr1)
let arr4=[...arr1,...arr2]
console.log(arr4)
let arr5=[1,2,3,[2,3,4,[5,6,7]]]
console.log(arr5.flat(2))
console.log(Array.isArray("sourav"))
console.log(Array.from("sourav"))
console.log(Array.fromkey({1:"sourav",2:"dhillon"}))